export const plantItems = [
  {name:'Gummiakazie',source:'Acacia_Senegal_Gummiakazie_Ausschnitt'},
  {name:'Ananas',source:'Ananas_sativus_Schult. _Ananas_Ausschnitt'},
  {name:'Mohrenhirse',source:'Andropogon_Sorghum_Brotero_var._Durrha._Mohrenhirse_Ausschnitt', description: 'Andropogon Sorghum Brotero'},
  {name:'Erdnuss',source:'Arachis_hypogaea_Linné_Erdnuss_Ausschnitt'},
  {name:'Erdnuss Indischer Sesam',source:'Arachis_hypogaea,_Sesamum_indicum,_Sesamum_orientale_Erdnuss_Indischer_Sesam_Weißer_Sesam_Ausschnitt'},
  {name:'Traganthstrauch',source:'Astragalus_creticus_Lam. _Cretischer_Traganthstrauch_Ausschnitt'},
  {name:'Gemeines Bambusrohr',source:'Bambusa_arundinacea_Willd. _Gemeines_Bambusrohr_Ausschnitt'},
  {name:'Butterbaum',source:'Butyrospermum_Parkii_Kotschy,_Illipe_latifolia_Engler_Afrikanischer_Butterbaum,_Mahwabaum_Ausschnitt'},
  {name:'Spanischer Pfeffer',source:'Capsicum_longum_DC._Spanischer_Pfeffer_I_Ausschnitt'},
  {name:'Spanischer Pfeffer II',source:'Capsicum_longum_DC._Spanischer_Pfeffer_II_Ausschnitt'},
  {name:'Papaya',source:'Carica_Papaya_Linné_Melonenbaum_Ausschnitt'},
  {name:'Edelkastanie',source:'Castanea_vulgaris_Edelkastanie_Ausschnitt'},
  {name:'Fieberrindenbaum',source:'Cinchona_Calisaya_var_ Josephiana_Weddell_Fieberrindenbaum_Ausschnitt'},
  {name:'Kampferbaum',source:'Cinnamomum_Camphora_Nees_et_Eberm._Kampferbaum_Ausschnitt'},
  {name:'Kolabaum',source:'Cola_acuminata_R._Brown_Kolabaum_Ausschnitt'},
  {name:'Eingerollte Farnpalme II',source:'Cycas_circinalis_Linné_Eingerollte_Farnpalme_2tes_Teil_Ausschnitt'},
  {name:'Eingerollte Farnpalme',source:'Cycas_circinalis_Linné_Eingerollte_Farnpalme_Ausschnitt'},
  {name:'Ebenholzbaum',source:'Diospyros_Dalechamps_Ebenholzbaum_Ausschnitt'},
  {name:'Echter Muskatnussbaum',source:'Echter_Muskatnussbaum_Ausschnitt'},
  {name:'Afrikanische Ölpalme',source:'Elaeis_guineensis_Linné_Afrikanische_Ölpalme_Ausschnitt'},
  {name:'Kardamompflanze',source:'Elettaria_cardamomum_White_Echte_Kardamompflanze_Ausschnitt'},
  {name:'Kardamom',source:'Elettaria_Cardamomum_White_et_Maton_Malobar_Cardamome_Ausschnitt'},
  {name:'Echter Gummiguttbaum',source:'Garcinia_Hanburyi_Hooker_L._Echter_Gummiguttbaum_Ausschnitt'},
  {name:'Kampecheholzbaum',source:'Haematoxylon_campecheanum_Linne_Kampecheholzbaum_Ausschnitt'},
  {name:'Amerikanischer Kopalbaum',source:'Hymenaea_Courbaril_L._Amerikanischer_Kopalbaum_Lokustbaum_Ausschnitt'},
  {name:'Amerikanischer Kopalbaum II',source:'Hymenaea_Courbaril_L._Amerikanischer_Kopalbaum_Lokustbaum_Teil2_Ausschnitt'},
  {name:'Amerikanischer Kopalbaum III',source:'Hymenaea_Courbaril_L._Amerikanischer_Kopalbaum_Lokustbaum_Teil3_Ausschnitt'},
  {name:'Paraguay Theestrauch',source:'Ilex_paraguariensis_St._Hilaire_Mate-Pflanze,_Paraguay_Theestrauch_Ausschnitt'},
  {name:'Indigopflanze',source:'Indigofera_tinctoria_Indigopflanze_Ausschnitt'},
  {name:'Gemeiner Walnussbaum',source:'Juglans_regia_Gemeiner_Walnussbaum_Ausschnitt'},
  {name:'Gemeiner Walnussbaum II',source:'Juglans_regia_Gemeiner_Walnussbaum_Teil2_Ausschnitt'},
  {name:'Schönblühende Kautschukliane',source:'Landolphia_comorensis,_var._florida_K._Schumann _Schönblühende_Kautschukliane_Ausschnitt'},
  {name:'Schönblühende Kautschukliane II',source:'Landolphia_comorensis,_var._florida_K._Schumann _Schönblühende_Kautschukliane_Teil2_Ausschnitt'},
  {name:'Schönblühende Kautschukliane III',source:'Landolphia_comorensis,_var._florida_K._Schumann _Schönblühende_Kautschukliane_Teil3_Ausschnitt'},
  {name:'Maniokstrauch',source:'Manihot_utilissima_Pohl_Maniok-_oder_Cassavestrauch_Ausschnitt'},
  {name:'Pfeilwurz',source:'Maranta_arundinacea_L. _Pfeilwurz_Ausschnitt'},
  {name:'Pfeilwurz II',source:'Maranta_arundinacea_L. _Pfeilwurz_Teil2_Ausschnitt'},
  {name:'Pfeilwurz III',source:'Maranta_arundinacea_L. _Pfeilwurz_Teil3_Ausschnitt'},
  {name:'Muskatnussbaum',source:'Myristica_fragrans_Houttuyn_Muskatnussbaum_Ausschnitt'},
  {name:'Muskatnussbaum II',source:'Myristica_fragrans_Houttuyn_Muskatnussbaum_Teil2_Ausschnitt'},
  {name:'Neuseeländischer Flachs',source:'Phormium_tenax,_Agave_americana_Neuseeländischer_Flachs_Amerikanische_Agave_Ausschnitt'},
  {name:'Indischer Sesam',source:'Sesamum_indicum_Linné_Sesamum_orientale_Linné_Indischer_Sesam_Weisser_Sesam_Ausschnitt'},
  {name:'Indischer Sesam II',source:'Sesamum_indicum_Linné_Sesamum_orientale_Linné_Indischer_Sesam_Weisser_Sesam_Teil2_Ausschnitt'},
  {name:'Brechnussbaum',source:'Strychnos_nux_vomica_L._Brechnussbaum_Ausschnitt'},
  {name:'Amerikanischer Mahagonibaum',source:'Swietenia_Mahagoni_L._Amerikanischer_Mahagonibaum_Ausschnitt'},
  {name:'Theestrauch',source:'Thea_chinensis_Linné_Theestrauch_Ausschnitt'},
  {name:'Kakaobaum',source:'Theobroma_Cacao_Linné_Kakaobaum_Ausschnitt'},
  {name:'Vanille',source:'Vanilla_planifolia_Andrews_Vanille_Ausschnitt'},
  {name:'Echter Ingwer',source:'Zingiber_officinale_Roscoe_Echter_Ingwer_Ausschnitt'},
  {name:'Echter Ingwer II',source:'Zingiber_officinale_Roscoe_Echter_Ingwer_Teil2_Ausschnitt'}
  
]

export default plantItems;
